from .CategoryCrud.CategoryList import *
from .CategoryCrud.CategoryDetail import *
from .CategoryCrud.CategoryDelete import *
from .BrandCrud.BrandDetail import *
from .BrandCrud.BrandList import *
from .BrandCrud.BrandDelete import *
from .BrandCrud.BrandUpdate import *
from .ProductCrud.ProductList import *
from .ProductCrud.ProductDetail import *
from .ProductCrud.ProductDelete import *
from .ProductCrud.ProductUpdate import *
from .ProductCrud.ProductCreate import *
from .ProductVariantCrud.ProductVariantList import *
from .ProductVariantCrud.ProductVariantDetail import *
from .ProductVariantCrud.ProductVariantDelete import *
from .ProductVariantCrud.ProductVariantUpdate import *
from .ProductVariantCrud.ProductVariantCreate import *
